// Party Royale — original overworld pixel art (outdoor tiles). 16x16 art px per map tile, shown at 2x.
// Shape: { name: {w, h, pal:{char:'#rrggbb'}, rows:[h strings of w chars]} }, '.' = transparent.
// Light comes from the top-left; outlines are dark tinted colours (not pure black), Gen 3 style.

const GRASS = {G:'#48d890', l:'#78f0b0', d:'#34c07c', s:'#30a870'};
const EARTH = {k:'#5a3020', E:'#d89068', e:'#b06840', D:'#804828'};
const WATER = {W:'#58a0f0', u:'#88c0f8', w:'#d0ecff', D:'#4888e0'};
const SAND  = {P:'#e8d8a0', q:'#d4c080', s:'#f4e8c0'};
const WALL  = {c:'#f4ecd4', d:'#d8ccb0', e:'#b8a888', k:'#302830'};

const g16 = 'GGGGGGGGGGGGGGGG';
const mirror = t => ({...t, rows: t.rows.map(r => [...r].reverse().join(''))});

const ledge_e = {w:16, h:16, pal:{...GRASS, ...EARTH}, rows:[
  'GGGGGlkEEEeksGGG',
  'GGGGGlkEeeeDkGGG',
  'GdGdGlkEeeeDkGGG',
  'GGdGGlkEeeDDkGGG',
  'GGGGGlkeeeDDkGGG',
  'GGGGGlkeeDDksGGG',
  'GGGGGlkkkkkksGGG',
  'GGGGGlkEEEeksGGG',
  'GGGGGlkEEEeksGGG',
  'GGGGGlkEeeeDkGGG',
  'GGGGGlkEeeeDkGGG',
  'GGGGGlkEeeDDkGGG',
  'GGGdGlkeeeDDkGGG',
  'GGGGGlkeeDDksGGG',
  'GGGGGlkkkkkksGGG',
  'GGGGGlkEEEeksGGG',
]};

module.exports = {
  grass_v0: {w:16, h:16, pal:GRASS, rows:[
    g16,
    'GGGlGGGGGGGGGGGG',
    'GGGdGdGGGGGGGGGG',
    'GGGGdGGGGGGGGGGG',
    'GGGGGGGGGGGGlGGG',
    g16, g16, g16, g16,
    'GGGGGGGGGGdGdGGG',
    'GGlGGGGGGGGdGGGG',
    g16, g16, g16, g16, g16,
  ]},
  grass_v1: {w:16, h:16, pal:GRASS, rows:[
    g16, g16,
    'GGGGGGGGGlGGGGGG',
    'GGGGGGGGGdGdGGGG',
    'GGGGGGGGGGdGGGGG',
    g16, g16,
    'GGGGGGlGGGGGGGGG',
    g16, g16, g16,
    'GGdGdGGGGGGGGGGG',
    'GGGdGGGGGGGGGGGG',
    g16,
    'GGGGGGGGGGGGGlGG',
    g16,
  ]},
  grass_v2: {w:16, h:16, pal:GRASS, rows:[
    g16, g16,
    'GGGGGGGGGGGGlGGG',
    g16,
    'GGGGlGGGGGGGGGGG',
    g16, g16, g16, g16, g16, g16,
    'GGGGGGGGGGGlGGGG',
    'GGGGGGGdGdGGGGGG',
    'GGGGGGGGdGGGGGGG',
    g16, g16,
  ]},
  grass_v3: {w:16, h:16, pal:GRASS, rows:[
    g16, g16, g16,
    'GGGlGGGGGGGGGGGG',
    'GGGGGGGGGGGlGGGG',
    'GGGGGGGGGGGdGdGG',
    'GGGGGGGGGGGGdGGG',
    g16, g16, g16,
    'GGGGGdGGGGGGGGGG',
    g16, g16,
    'GGGGGGGGlGGGGGGG',
    g16, g16,
  ]},

  path: {w:16, h:16, pal:SAND, rows:[
    'PPPPPPPPPPPPPPPP',
    'PPPPPPPPPPPsPPPP',
    'PPqPPPPPPPPPPPPP',
    'PPPPPPPPPPPPPPPP',
    'PPPPPPPqqPPPPPPP',
    'PPPPPPPPPPPPPPsP',
    'PsPPPPPPPPPPPPPP',
    'PPPPPPPPPPPPPPPP',
    'PPPPPPPPPPPqPPPP',
    'PPPPsPPPPPPPPPPP',
    'PPPPPPPPPPPPPPPP',
    'PPqqPPPPPPPPPPPP',
    'PPPPPPPPPPsPPPPP',
    'PPPPPPPPPPPPPqPP',
    'PPPPPPsPPPPPPPPP',
    'PPPPPPPPPPPPPPPP',
  ]},

  // Two ripple crests per tile; the second one wraps across the left/right edge so tiles join seamlessly.
  water: {w:16, h:16, pal:WATER, rows:[
    'WWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWW',
    'WWWWuuwwuWWWWWWW',
    'WWWuWWWWWuuWWWWW',
    'WWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWDDWW',
    'WWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWW',
    'uWWWWWWWWWWWuuww',
    'WuuWWWWWWWWuWWWW',
    'WWWWWWWWWWWWWWWW',
    'WWWDDWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWW',
  ]},
  water_b: {w:16, h:16, pal:WATER, rows:[
    'WWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWW',
    'WWWWWuuwwuWWWWWW',
    'WWWWuWWWWWuuWWWW',
    'WWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWDDWWW',
    'WWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWuuwwu',
    'uuWWWWWWWWuWWWWW',
    'WWWWWWWWWWWWWWWW',
    'WWWWDDWWWWWWWWWW',
    'WWWWWWWWWWWWWWWW',
    'WWWWWWWWWWWWWWWW',
  ]},

  // Red + white flower on transparent (draw over grass). Frame b: heads sway 1px, leaves stay.
  flower: {w:16, h:16, pal:{L:'#f89890', P:'#e84848', S:'#b02838', Y:'#f8e048', a:'#ffffff', b:'#e0e0ec', c:'#a8a8c0', v:'#58c878', n:'#289050'}, rows:[
    '................',
    '..LL.PP.........',
    '.LLL.PPP........',
    '.LLLYPPP........',
    '...YYY..........',
    '.PPPYSSS........',
    '.PPP.SSS........',
    '..PP.SS.........',
    '.vn...nv.aa.bb..',
    '........aaa.bbb.',
    '........aaaYbbb.',
    '..........YYY...',
    '........bbbYccc.',
    '........bbb.ccc.',
    '.........bb.cc..',
    '........vn...nv.',
  ]},
  flower_b: {w:16, h:16, pal:{L:'#f89890', P:'#e84848', S:'#b02838', Y:'#f8e048', a:'#ffffff', b:'#e0e0ec', c:'#a8a8c0', v:'#58c878', n:'#289050'}, rows:[
    '................',
    '...LL.PP........',
    '..LLL.PPP.......',
    '..LLLYPPP.......',
    '....YYY.........',
    '..PPPYSSS.......',
    '..PPP.SSS.......',
    '...PP.SS........',
    '.vn...nvaa.bb...',
    '.......aaa.bbb..',
    '.......aaaYbbb..',
    '.........YYY....',
    '.......bbbYccc..',
    '.......bbb.ccc..',
    '........bb.cc...',
    '........vn...nv.',
  ]},

  rock: {w:16, h:16, pal:{k:'#404048', H:'#f0f0e8', L:'#c8c8c0', M:'#a0a098', D:'#707068', g:GRASS.s}, rows:[
    '................',
    '................',
    '......kkkkk.....',
    '....kkHHLLLkk...',
    '...kHHLLLLLMMk..',
    '..kHLLLLLLMMMMk.',
    '..kLLLLLLMMMMMk.',
    '.kLLLLLMMMMMMDk.',
    '.kLLLMMMMMMMDDk.',
    '.kMMMMMkMMMDDDk.',
    '.kMMMMMMkMDDDDk.',
    '.kMMMMMMDDDDDDk.',
    '..kDDDDDDDDDDk..',
    '..gkkkkkkkkkkgg.',
    '...gggggggggg...',
    '................',
  ]},

  // White wooden fence; rails run edge to edge so it tiles horizontally.
  fence: {w:16, h:16, pal:{k:'#584838', w:'#f8f4e8', m:'#e0d4b8', s:'#b8a888', g:GRASS.s}, rows:[
    '................',
    '................',
    '......kkk.......',
    '.....kwmsk......',
    '.....kwmsk......',
    'kkkkkkwmskkkkkkk',
    'wwwwwkwmskwwwwww',
    'mmmmmkwmskmmmmmm',
    'kkkkkkwmskkkkkkk',
    '.....kwmsk......',
    'kkkkkkwmskkkkkkk',
    'wwwwwkwmskwwwwww',
    'mmmmmkwmskmmmmmm',
    'kkkkkkwmskkkkkkk',
    'gggggkwmskgggggg',
    '.....kkkkkg.....',
  ]},

  sign: {w:16, h:16, pal:{k:'#503018', L:'#f0c078', M:'#d89850', D:'#b07030', t:'#704020', p:'#9a6838', P:'#6a4020', g:GRASS.s}, rows:[
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kLLLLLLLLLLLLk.',
    '.kLMMMMMMMMMMDk.',
    '.kLMttMtttMtMDk.',
    '.kLMMMMMMMMMMDk.',
    '.kLMtttMttMMMDk.',
    '.kLMMMMMMMMMMDk.',
    '.kDDDDDDDDDDDDk.',
    '.kkkkkkkkkkkkkk.',
    '......kpPk......',
    '......kpPk......',
    '......kpPk......',
    '......kpPk......',
    '.....gkpPkg.....',
    '......gggg......',
  ]},

  // Route marker: blue metal plate with a white arrow, on two steel legs.
  rsign: {w:16, h:16, pal:{k:'#283048', H:'#88a8e8', B:'#4870c8', b:'#3050a0', w:'#f8f8f8', s:'#d0d8e0', S:'#8890a0', g:GRASS.s}, rows:[
    '................',
    'kkkkkkkkkkkkkkkk',
    'kHHHHHHHHHHHHHHk',
    'kHBBBBBBBBBBBBbk',
    'kHBwwwwBBBBwBBbk',
    'kHBBBBBBBBBwwBbk',
    'kHBwwwBBwwwwwwbk',
    'kHBBBBBBBBBwwBbk',
    'kHBwwwwBBBBwBBbk',
    'kbbbbbbbbbbbbbbk',
    'kkkkkkkkkkkkkkkk',
    '..ksSk....ksSk..',
    '..ksSk....ksSk..',
    '..ksSk....ksSk..',
    '..ksSk....ksSk..',
    '.gkkkkg..gkkkkg.',
  ]},

  // Item ball lying in the grass (own design: a slightly squat ball with a big top-left glint).
  item: {w:16, h:16, pal:{k:'#282028', R:'#f04838', r:'#b82828', H:'#f8b0a0', W:'#f8f8f8', w:'#c0c0d0', g:GRASS.s}, rows:[
    '................',
    '................',
    '................',
    '......kkkk......',
    '....kkRRRRkk....',
    '...kHRRRRRRrk...',
    '..kHHRRRRRRRrk..',
    '..kHRRRRRRRrrk..',
    '..kkkkkWWkkkkk..',
    '..kWWWkWwkWwwk..',
    '..kWWWWWWWWwwk..',
    '...kWWWWWWwwk...',
    '....kkwwwwkk....',
    '...gggkkkkggg...',
    '....gggggggg....',
    '................',
  ]},

  // South-facing ledge: grass on top, a lit rim, then a scalloped earth lip and its shadow.
  ledge: {w:16, h:16, pal:{...GRASS, ...EARTH}, rows:[
    g16,
    'GGGlGGGGGGGGGGGG',
    'GGGdGdGGGGGGGGGG',
    'GGGGdGGGGGGGGGGG',
    g16,
    'llllllllllllllll',
    'kkkkkkkkkkkkkkkk',
    'EEEEEEekEEEEEEek',
    'EeeeeeDkEeeeeeDk',
    'eeeeeDDkeeeeeDDk',
    'keeDDDkkkeeDDDkk',
    'skkkkkksskkkkkks',
    'ssssssssssssssss',
    g16,
    'GGGGGGGGGGGdGdGG',
    'GGGGGGGGGGGGdGGG',
  ]},
  ledge_e,
  ledge_w: mirror(ledge_e),

  // Gym entrance statue: stone orb on a plinth with a brass plaque. 24 tall = overhangs 8px into the tile above.
  statue: {w:16, h:24, pal:{k:'#303038', R:'#e04848', r:'#a82830', H:'#f8a8a8', W:'#f0f0f8', L:'#c8c8d0', M:'#a0a0b0', D:'#707080', Y:'#f8d060', y:'#c09830'}, rows:[
    '................',
    '......kkkk......',
    '....kkRRRRkk....',
    '...kHRRRRRRrk...',
    '..kHHRRRRRRRrk..',
    '..kHRRRRRRRrrk..',
    '..kkkkkWWkkkkk..',
    '..kLLLkLMkMMMk..',
    '..kLLLLLLLMMDk..',
    '...kLLLLLMMDk...',
    '....kkMMMMkk....',
    '.....kkkkkk.....',
    '.kkkkkkkkkkkkkk.',
    '.kWWWWWWWWWWWWk.',
    '.kLLLLLLLLLLLMk.',
    '.kkkkkkkkkkkkkk.',
    '..kLLLLLLLLLMk..',
    '..kLkkkkkkkkMk..',
    '..kLkYYYYYYkMk..',
    '..kLkyyyyyykMk..',
    '..kLkkkkkkkkMk..',
    '..kLLLMMMMMMDk..',
    '.kMMMMMMMMMMMMk.',
    '.kkkkkkkkkkkkkk.',
  ]},

};
