// Story props. tablet: a Tidewarden stone tablet (16x24; the top 8 px stand over the tile above),
// weathered stone with glowing teal script, on a plinth with a grass shadow.
module.exports = {
  tablet: {w:16, h:24, pal:{k:'#2e3440', a:'#d4d8e0', b:'#a4aab6', c:'#6c7280', g:'#3ab0a8', s:'#34b47c'}, rows:[
    '................',
    '................',
    '....kkkkkkkk....',
    '...kaaaaaaabk...',
    '..kaaabbbbaabk..',
    '..kagggggggabk..',
    '..kabbbbbbbbck..',
    '..kaggbgggbgck..',
    '..kabbbbbbbbck..',
    '..kagggbggggck..',
    '..kabbbbbbbbck..',
    '..kaggggbgggck..',
    '..kabbbbbbbbck..',
    '..kagbgggbggck..',
    '..kabbbbbbbbck..',
    '..kbbbbbbbbbck..',
    '..kcccccccccck..',
    '..kkkkkkkkkkkk..',
    '..kbbbbbbbbbbk..',
    '.kbbccccccccbbk.',
    '.kkkkkkkkkkkkkk.',
    '..ssssssssssss..',
    '................',
    '................',
  ]},
};
