// Party Royale overworld trees - original pixel art (Gen-3 style, light from top-left).
// 16px wide. tree/tree2: h=24, rows 0-7 overhang the tile above, rows 8-23 are the tree's own tile.
// 's' is a painted grass shadow (darker than grass #48d890); it fills the gaps between trees in a forest block.
const PAL = {k:'#101810', d:'#286428', m:'#3e9c32', l:'#78c84a', h:'#bcf07c', t:'#8a6a40', u:'#4e361e', s:'#34b47c'};
module.exports = {
  tree: {w:16, h:24, pal:PAL, rows:[
    '................',
    '................',
    '......kkkk......',
    '....kkhhhlkk....',
    '..kkkhhhlllmkkk.',
    '.khhhkhlllmmdlk.',
    'khhhlldlmlmddllk',
    'khhlllmdddddhhlk',
    'khlhlmmdhhlhlmmk',
    'klllmmdhhllmmmdk',
    'kmlmddhlhllmdmdk',
    'khhddlllllmmddhk',
    'khlhmdllmlmmdhlk',
    'klmdmddmmdmddlmk',
    'kmmddkddddddkmdk',
    'skmlmmddkmlmddks',
    'skdmmdddkdmddkks',
    'sskdddkkkdddkkss',
    'ssskkkuuuukkksss',
    '.sssskttuukssss.',
    'sssskkttuukkssss',
    'sssssskkkkssssss',
    '.ssssssssssssss.',
    '...ssssssssss...'
  ]},
  tree2: {w:16, h:24, pal:PAL, rows:[
    '................',
    '................',
    '.....kkkk.......',
    '...kkhhhlkkk....',
    '..khhhhllmkhlkk.',
    '.khhhlllmmdhllk.',
    'khhlhllmmddhlhmk',
    'khlllmmdddlllmdk',
    'klhlmddhhhdlmmdk',
    'kmmmdhhllllddddk',
    'kdmddhlhllmmhhlk',
    'khhlddlllmmdllmk',
    'khlhmdmlmmddlmmk',
    'klmdmddmdddmmmdk',
    'kmmddkmhllmddddk',
    'skdddmllmmmdddks',
    'skkddmmmddddddks',
    'sskkdddddddkkkss',
    'ssskkkuuuukkksss',
    '.sssskttuukssss.',
    'sssskkttuukkssss',
    'sssssskkkkssssss',
    '.ssssssssssssss.',
    '...ssssssssss...'
  ]},
  bush: {w:16, h:16, pal:PAL, rows:[
    '................',
    '................',
    '................',
    '....kkkk.kkk....',
    '...khhhlkhllk...',
    '..khhllldhlllmk.',
    '.khhllmdmdllmmk.',
    '.khllmmdhhlllmdk',
    'khlhlmdhhlhllmdk',
    'klllmdhllllmmddk',
    'kmlmdlhlmmlmdmdk',
    'kdmmdmmmmmdddkdk',
    '.kdddmmmddddkdk.',
    '.skkddddddddkks.',
    '.sskkkkkkkkkkss.',
    '...ssssssssss...'
  ]}
};
