#!/usr/bin/env python3
"""GBA 1.8: evolutions the level-up data misses, egg groups, base forms and TM compatibility, from PokeAPI's CSVs
(https://github.com/PokeAPI/pokeapi/tree/master/data/v2/csv), into data/extras.json. build_assets.py keeps what
fits the game's own species and moves.

    python3 tools/build_extras.py path/to/csv-folder

Needs pokemon_species.csv, pokemon_evolution.csv, items.csv, pokemon_egg_groups.csv, machines.csv, moves.csv and
pokemon_moves.csv.
"""
import csv
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
USUM = '18'             # version group: Ultra Sun / Ultra Moon, as js/dexdata.js
LATER = ['20', '25']    # Sword / Shield, Scarlet / Violet: TM moves for species USUM doesn't have

# Items that evolve a Pokémon when used on it. Trades (held item or not) all take the LINKING CORD; a few
# special cases take the stone that later games switched them to.
STONES = {'fire-stone', 'water-stone', 'thunder-stone', 'leaf-stone', 'moon-stone', 'sun-stone', 'shiny-stone',
          'dusk-stone', 'dawn-stone', 'ice-stone'}
HELD_USE = {'oval-stone', 'razor-claw', 'razor-fang'}
SPECIAL = {('eevee', 'espeon'): 'sun-stone', ('eevee', 'umbreon'): 'moon-stone', ('eevee', 'sylveon'): 'shiny-stone',
           ('eevee', 'leafeon'): 'leaf-stone', ('eevee', 'glaceon'): 'ice-stone',
           ('magneton', 'magnezone'): 'thunder-stone', ('nosepass', 'probopass'): 'thunder-stone',
           ('cosmoem', 'lunala'): 'moon-stone', ('feebas', 'milotic'): 'linking-cord'}


def main(folder):
    rd = lambda f: list(csv.DictReader(open(os.path.join(folder, f + '.csv'), encoding='utf-8')))
    species = {int(r['id']): r for r in rd('pokemon_species')}
    ident = {i: r['identifier'] for i, r in species.items()}
    items = {r['id']: r['identifier'] for r in rd('items')}
    evolves_from = {i: int(r['evolves_from_species_id']) for i, r in species.items() if r['evolves_from_species_id']}

    evo = []
    seen = set()
    for r in rd('pokemon_evolution'):
        to = int(r['evolved_species_id'])
        fr = evolves_from.get(to)
        if not fr or r['evolved_pokemon_form_id'] or r['region_id']:
            continue        # regional forms
        key = (ident[fr], ident[to])
        trigger = r['evolution_trigger_id']
        item = None
        if key in SPECIAL:
            item = SPECIAL[key]
        elif trigger == '3' and items.get(r['trigger_item_id']) in STONES:
            item = items[r['trigger_item_id']]
        elif trigger == '2':
            item = 'linking-cord'
        elif trigger == '1' and items.get(r['held_item_id']) in HELD_USE:
            item = items[r['held_item_id']]
        if item:
            entry = {'from': fr, 'to': to, 'item': item}
        elif trigger == '1' and not r['minimum_level']:
            entry = {'from': fr, 'to': to, 'level': 0}     # friendship, a move, a place...: a level (build_assets)
        elif trigger == '1':
            entry = {'from': fr, 'to': to, 'level': int(r['minimum_level'])}
        else:
            continue
        k = (fr, to, entry.get('item'))
        if k not in seen and not any((fr, to) == s[:2] for s in seen):
            seen.add(k)
            evo.append(entry)

    eggs = {}
    for r in rd('pokemon_egg_groups'):
        eggs.setdefault(int(r['species_id']), []).append(int(r['egg_group_id']))

    move_name = {r['id']: r['identifier'] for r in rd('moves')}
    tms = []
    for r in rd('machines'):
        if r['version_group_id'] == USUM and int(r['machine_number']) <= 100:
            tms.append({'tm': int(r['machine_number']), 'move': move_name[r['move_id']]})
    tms.sort(key=lambda t: t['tm'])
    tm_moves = {t['move'] for t in tms}
    compat = {}
    later = {}
    for r in rd('pokemon_moves'):
        if r['pokemon_move_method_id'] != '4':
            continue
        pid = int(r['pokemon_id'])
        if pid not in species:
            continue
        m = move_name.get(r['move_id'])
        if m not in tm_moves:
            continue
        if r['version_group_id'] == USUM:
            compat.setdefault(pid, set()).add(m)
        elif r['version_group_id'] in LATER:
            later.setdefault(pid, set()).add(m)
    for pid, ms in later.items():
        if pid not in compat:
            compat[pid] = ms

    out = {
        '_howto': 'Generated by tools/build_extras.py from PokeAPI CSVs; do not edit.',
        'evolutions': evo,
        'egg_groups': {str(k): v for k, v in sorted(eggs.items())},
        'evolves_from': {str(k): v for k, v in sorted(evolves_from.items())},
        'tms': tms,
        'tm_compat': {str(k): sorted(v) for k, v in sorted(compat.items())},
    }
    path = os.path.join(HERE, '..', 'data', 'extras.json')
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(out, f, separators=(',', ':'), sort_keys=True)
    print('wrote data/extras.json: %d evolutions, %d TMs, %d species with TMs' % (len(evo), len(tms), len(compat)))


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
