// Builds js/dexinfo.js (Pokédex height, weight and category) from two PokeAPI CSVs:
// pokemon.csv and pokemon_species_names.csv (https://github.com/PokeAPI/pokeapi/tree/master/data/v2/csv).
// Usage: node tools/build-dexinfo.js <folder with those two CSVs>
// Output: DEXINFO[pokeapi id] = {h: decimetres, w: hectograms, g: "Seed"} for every species in the
// game (the DEX_NUM table in js/app.js). Pokédex description text is left out on purpose.
const fs = require('fs'), path = require('path');
const SRC = process.argv[2];
if(!SRC){ console.error('usage: node tools/build-dexinfo.js <csv folder>'); process.exit(1); }
const ROOT = path.join(__dirname, '..');

// Simple CSV rows (neither file has quoted commas in the columns we read).
const rows = file => {
  const [head, ...lines] = fs.readFileSync(path.join(SRC, file), 'utf8').replace(/^﻿/, '').split(/\r?\n/).filter(Boolean);
  const keys = head.split(',');
  return lines.map(l=>{ const v = l.split(','); return Object.fromEntries(keys.map((k,i)=>[k, v[i]])); });
};

const app = fs.readFileSync(path.join(ROOT, 'js', 'app.js'), 'utf8');
const ids = new Set([...app.match(/const DEX_NUM = \{([\s\S]*?)\};/)[1].matchAll(/":(\d+)/g)].map(m=>m[1]));

const genus = {};
for(const r of rows('pokemon_species_names.csv')) if(r.local_language_id==='9' && r.genus) genus[r.pokemon_species_id] = r.genus.replace(/ Pokémon$/, '');

const out = {};
for(const r of rows('pokemon.csv')) if(ids.has(r.id)) out[r.id] = {h:+r.height, w:+r.weight, g:genus[r.species_id] || ''};

fs.writeFileSync(path.join(ROOT, 'js', 'dexinfo.js'),
  '// Generated by tools/build-dexinfo.js from PokeAPI data (https://pokeapi.co) — do not edit by hand.\n' +
  '// DEXINFO[id] = {h: height in decimetres, w: weight in hectograms, g: category}\n' +
  'const DEXINFO = ' + JSON.stringify(out) + ';\n');
console.log(`wrote ${Object.keys(out).length} of ${ids.size} species`);
