// Builds js/tileart.js (TILE_ART) from the pixel-art sources in tools/art/*.js.
// Each entry is {w, h, pal:{char:'#rrggbb'}, rows:[h strings of w chars, '.' = transparent]}.
// Run: node tools/build-tileart.js
const fs = require('fs'), path = require('path');
const dir = path.join(__dirname, 'art'), art = {};
for(const f of fs.readdirSync(dir).filter(f=>f.endsWith('.js')).sort()){
  const mod = require(path.join(dir, f));
  for(const [name, a] of Object.entries(mod)){
    if(art[name]) throw new Error(`${f}: duplicate tile "${name}"`);
    if(a.rows.length!==a.h || a.rows.some(r=>r.length!==a.w)) throw new Error(`${f}: "${name}" is not ${a.w}x${a.h}`);
    for(const r of a.rows) for(const ch of r) if(ch!=='.' && !a.pal[ch]) throw new Error(`${f}: "${name}" uses "${ch}" with no palette entry`);
    art[name] = {w:a.w, h:a.h, pal:a.pal, rows:a.rows};
  }
}
fs.writeFileSync(path.join(__dirname, '..', 'js', 'tileart.js'),
  `// Generated by tools/build-tileart.js from tools/art/*.js; edit those, not this.\nconst TILE_ART = ${JSON.stringify(art)};\n`);
console.log(`js/tileart.js: ${Object.keys(art).length} tiles`);
